const path = require('path');
const {CleanWebpackPlugin} = require('clean-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
  },
  // performance: {
  //   maxAssetSize: 500000, 
  // },
  devtool: 'inline-source-map',
  devServer: {
    static: path.resolve(__dirname, 'dist'),
    port: 8564,
    hot: true
  },
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.(png|jpeg|jpg|gif|svg)$/i,
        type: 'asset/resource',
      },
    ],
  },
  // plugins: [
  //   new CleanWebpackPlugin({ 
  //     cleanStaleWebpackAssets: false  // dont clean stale assets like index.html generated by plugin
  //   })
  // ],
  // optimization: {
  //   runtimeChunk: 'single',   // to use multiple entry points in single page
  //   // could also use `dependOn` property in entry modules for splitting
  //   splitChunks: {
  //     cacheGroups: {
  //       vendor: {
  //         test: /[\\/]node_modules[\\/]/,
  //         name: 'vendors',
  //         chunks: 'all',
  //       },
  //     },
  //   },
  // },
};
